<definition>
	<command name="type">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>

		<case locator-key1="DISPLAY_DATE_DATE_INPUT">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="DISPLAY_DATE_TIME_INPUT">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="EXPIRATION_DATE_DATE_INPUT">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="EXPIRATION_DATE_TIME_INPUT">
			<execute function="Type#clickAtSendKeys" />
		</case>
	</command>
</definition>