<definition>
	<command name="assertClick">
		<case locator-key1="SAVE_BUTTON">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="ANSWER_FIELD">
			<execute function="IsElementPresent#pauseIsElementPresent" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="ANSWER_FIELD">
			<execute function="Type#pauseType" />
		</case>
	</command>
</definition>